/**
 * The offline dictionary for Word Duel.
 *
 * Bundled, not downloaded: AirLink must work with the radio off, so every word
 * the game will ever accept ships inside the app. Roughly four thousand common
 * English words of three to eight letters - long enough to be satisfying, short
 * enough that a 4x4 grid can actually contain them.
 *
 * Stored as space-separated runs rather than a JSON array purely for size: it
 * is the same data with a fraction of the punctuation, and it parses once at
 * module load into a sorted array that `isWord` searches by bisection.
 */

const PACKED: readonly string[] = [
  'ace ache acid acorn acre act acted actor add adder admit ado adopt adore adult afar after again age',
  'aged agent ago aid aide ail aim air airy aisle ajar alarm alas albeit ale alert alias alibi alien',
  'align alike alive all alley allow alloy ally almond almost alms aloe alone along aloud alp altar alter',
  'amber amble amend amid amiss among ample amuse anchor and anew angel anger angle angry ankle annoy',
  'answer ant ante anthem antic anvil any apart ape apex apple apply apron apt aqua arc arch are area',
  'arena argue arid arise arm armor army aroma arose array arrow art artist ash aside ask asleep aspen',
  'assert asset aster astir ate atlas atom attic auburn audit auger augur aunt aura auto autumn avail',
  'avenue avert avid avoid await awake award aware away awe awful awoke axe axis axle babe baby back',
  'bacon bad badge badly bag bake baker bald bale ball balm ban band bandit bang bank bar barb bard bare',
  'barge bark barley barn baron barrel base basic basil basin basket bass baste bat batch bath baton',
  'batter bay bead beam bean bear beard beast beat beauty beaver became beckon become bed bee beech beef',
  'been beer beet beetle before beg began beggar begin begun behave behind being belief bell belly below',
  'belt bench bend beneath bent berry berth beside best bet beta betray better bevel beware beyond bias',
  'bib bicycle bid big bike bill billow bin bind biology birch bird birth biscuit bishop bison bit bite',
  'bitter black blade blame bland blank blast blaze bleak bleat bleed blend bless blew blind blink bliss',
  'blitz blob block blond blood bloom blot blow blue bluff blunt blur blush boar board boast boat bob',
  'bode body bog boil bold bolt bomb bond bone bonnet bonus book boom boost boot booth border bore born',
  'borrow bosom boss both bother bottle bottom bought bounce bound bounty bout bow bowl box boy brace',
  'brag braid brain brake bran branch brand brass brave bread break breast breath breed breeze brew briar',
  'brick bride brief brier bright brim brine bring brink brisk broad broil broke bronze brook broom broth',
  'brow brown bruise brunt brush brute bubble buck bucket bud budge buffet bug build built bulb bulk',
  'bull bullet bump bunch bundle bunk bunny burden bureau burn burnt burrow burst bury bus bush bust',
  'busy but butler butter button buy buzz cab cabin cable cache cactus cadet cage cake calf call calm',
  'came camel camp can canal candle cane canoe canvas canyon cap cape car carbon card care cargo carol',
  'carpet carrot carry cart carve case cash cask cast castle cat catch cattle caught cause cave cease',
  'cedar ceiling cell cellar cement census cent center cereal chain chair chalk champ chance change chant',
  'chaos chapel char charm chart chase chat cheap cheat check cheek cheer cheese chef cherry chess chest',
  'chew chick chief child chill chime chin chip chirp choice choir choke chop chord chore chose chunk',
  'churn cider cigar cinch circle circus cite citrus city civic civil clad claim clam clamp clan clap',
  'clash clasp class claw clay clean clear cleft clerk clever click cliff climb cling clinic clip cloak',
  'clock clod clog close cloth cloud clout clove clown club clue clump clung coach coal coast coat coax',
  'cobalt cobra cock cocoa code coffee coil coin coke cold collar colon colony color colt comb combat',
  'come comedy comet comfort comic comma common compel concur condor cone confer conic cook cool coop',
  'cope copper copy coral cord core cork corn corner corral cost cot cottage cotton couch cough could',
  'count county coup courage course court cousin cove cover cow coward cozy crab crack cradle craft crag',
  'cram crane crank crash crate crave crawl craze crazy creak cream create credit creed creek creep crept',
  'crest crew crib cried crime crimp crisp critic croak crock crop cross crow crowd crown crude cruel',
  'cruise crumb crush crust cry crypt cub cube cubic cuckoo cuff cult cup curb curd cure curfew curl',
  'curse curve cushion custom cut cute cycle cynic dab dad daily dairy daisy dale dam damage dame damp',
  'dance dandy danger dare dark darn dart dash data date daub dawn day dazzle dead deaf deal dealt dean',
  'dear death debate debris debt debut decade decay deceit decent decide deck declare decor decoy decree',
  'deed deem deep deer defeat defect defend defer define defy degree deity delay delta deluge demand',
  'demon den denim dense dent deny depart depend depot depth deputy derby derive desert design desire',
  'desk detail detect deter detour device devil devote dew dial diary dice die diesel diet differ dig',
  'digest digit dill dim dime dine dinner dip dire direct dirt disc dish disk dismay ditch dive divert',
  'divide divine dizzy dock doctor dodge doe dog doll dollar dome domino donate done donkey donor doom',
  'door dose dot double doubt dough dove down dozen draft drag dragon drain drama drank drape draw drawn',
  'dread dream dress drew dried drift drill drink drip drive drone drop drove drown drug drum dry duchess',
  'duck duct dude due duel duet dug duke dull duly dumb dump dune dung dunk duo dusk dust duty dwarf',
  'dwell dwelt dye dying each eager eagle ear early earn earth ease east easy eat eaten eave ebb echo',
  'edge edible edit eel effect effort egg ego eight either eject elbow elder elect elegy elf elite elk',
  'elm else elude embark ember emblem embrace emerge emit empire employ empty enable enact enamel enchant',
  'encode end endure enemy energy enforce engage engine enjoy enlist enough enrich enroll ensue enter',
  'entire entry envelop envoy envy epic epoch equal equip equity era erase erect erode err errand error',
  'erupt escape escort essay estate esteem etch eternal ether ethic evade eve even event ever every evict',
  'evil evoke exact exalt exam exceed excel except excess excite excuse exempt exert exhale exhaust exhibit',
  'exile exist exit exotic expand expect expel expend expert expire explain export expose extend extent',
  'extra extreme eye fable fabric face fact factor fade fail faint fair fairy faith fake fall false fame',
  'family famine famous fan fancy fang far farce fare farm fast fat fatal fate father fatigue fault favor',
  'fawn fear feast feat feather feature fed fee feeble feed feel feet fell fellow felt female fence fend',
  'fern ferry fertile fervor festive fetch fever few fiber fiction fiddle field fiend fierce fiery fifteen',
  'fifth fifty fig fight figure file fill film filter filth final finch find fine finger finish finite',
  'fir fire firm first fiscal fish fist fit five fix flag flake flame flank flap flare flash flask flat',
  'flavor flaw flax flea fleck fled flee fleece fleet flesh flew flex flick flight fling flint flip flirt',
  'float flock flood floor flop floral flour flow flower flu fluid fluke flung flush flute flux fly foam',
  'focus fodder foe fog foil fold folk follow fond font food fool foot for forbid force ford forest forge',
  'forget fork form formal format former fort forth forty forum forward fossil foster fought foul found',
  'four fowl fox foyer fraction frail frame frank fraud fray freak free freeze freight french frenzy',
  'fresh friar friction friend fright fringe frisk frock frog from front frost froth frown froze fruit',
  'fudge fuel fulfil full fumble fume fun function fund funeral fungus funnel funny fur furl furnace',
  'furry further fury fuse fusion fuss future fuzzy gable gadget gag gain gait gala galaxy gale gall',
  'gallon gallop game gang gap gape garage garb garden gargle garlic garment garnet gas gash gasp gate',
  'gather gauge gaunt gave gawk gay gaze gear geese gem gender gene general genius gentle genuine germ',
  'get ghost giant gift gig gill gilt ginger giraffe girl girth give given glad glance gland glare glass',
  'glaze gleam glean glen glide glimpse glint glitter globe gloom glory gloss glove glow glue glum gnat',
  'gnaw goal goat goblin god gold golf gone gong good goose gore gorge gorilla gospel gossip got gouge',
  'gourd govern gown grab grace grade grain grand grant grape graph grasp grass grate grave gravel gravy',
  'gray graze grease great greed green greet grew grid grief grill grim grin grind grip grit groan groom',
  'groove grope gross ground group grouse grove grow growl grown growth grub gruff grumble guard guess',
  'guest guide guild guilt guitar gulf gull gully gulp gum gun gust gut gutter guy gypsy habit hack had',
  'hail hair half hall halt ham hammer hamper hand handle handy hang happen happy harbor hard hardy hare',
  'harm harp harsh harvest has haste hasty hat hatch hate haul haunt have haven havoc hawk hay hazard',
  'haze hazel head heal health heap hear heard heart heat heath heave heaven heavy hedge heed heel hefty',
  'height heir held helium hell helmet help hem hen her herb herd here hero heron hers hew hexagon hey',
  'hid hide high hike hill hilt him hind hinge hint hip hire his hiss hit hive hoard hoarse hobble hobby',
  'hockey hoe hog hoist hold hole hollow holy home honest honey honor hood hoof hook hoop hop hope horde',
  'horizon horn horse hose host hot hotel hound hour house hover how howl hub huddle hue huff hug huge',
  'hull hum human humble humid humor hump hunch hundred hung hunger hunt hurdle hurl hurry hurt hush',
  'husk hut hybrid hymn ice icon icy idea ideal idiom idle idol igloo ignite ignore ill image imagine',
  'imitate immune impact impair impart impel imply import impose impress improve impulse inbox inch incline',
  'income indeed index indoor induce infant infect infer inflate inform ingot inhale inherit inject injure',
  'ink inland inlet inmate inn inner input inquire insect insert inside insist inspect instal instant',
  'instead insult insure intact intend intent inter into invade invent invest invite invoke inward iodine',
  'iris iron irony island isle issue itch item ivory ivy jab jacket jade jail jam jangle jar jaunt javelin',
  'jaw jazz jealous jeans jeep jeer jelly jest jet jewel job jockey jog join joint joke jolly jolt jot',
  'journal journey joy judge jug juice july jumble jump junction june jungle junior junk jury just justice',
  'jut keen keep kelp kept kernel kettle key kick kid kill kiln kilt kin kind king kiss kit kitchen kite',
  'kitten knack knee kneel knew knife knight knit knob knock knot know known knuckle lab label labor',
  'lace lack lad ladder laden lady lag lagoon laid lair lake lamb lame lamp lance land lane lapse lard',
  'large lark laser lash last latch late lately later lathe latter laugh launch laundry lava law lawn',
  'lawyer lay layer lazy lead leaf league leak lean leap learn lease leash least leather leave led ledge',
  'leech leek leer left leg legacy legal legend legion lemon lend length lens lent leopard less lesson',
  'lest let letter level lever liable liar libel liberty library license lick lid lie life lift light',
  'like lilac lily limb lime limit limp line linen linger link lint lion lip liquid list listen lit liter',
  'little live liver lizard load loaf loan lobby lobe local lock locket locust lodge loft log logic loin',
  'lone long look loom loop loose loot lord lore lose loss lost lot lotion loud lounge louse love low',
  'lower loyal lucid luck lucky lull lumber lump lunar lunch lung lure lurk lush lust lute luxury lying',
  'lyric macro mad madam made magic magnet magpie maid mail maim main maize major make malice mall malt',
  'mammal man manage mane mango mania manner manor mantle manual many map maple marble march mare margin',
  'marine mark market marry marsh mart marvel mask mason mass mast master mat match mate math matter',
  'mature maul maxim may maybe mayor maze meadow meal mean meant measure meat medal media medic medium',
  'meek meet mellow melody melon melt member memo memory men menace mend mental mentor menu merchant',
  'mercy mere merge merit mermaid merry mesh mess metal meteor meter method mica mid midst might mild',
  'mile milk mill mimic mince mind mine mingle mini minor mint minus minute miracle mirror mirth misery',
  'miss mist mistake mix moan moat mob mobile mock mode model modem modern modest modify moist molar',
  'mold mole moment monarch money monk monkey month mood moon moor moose mop moral morale morbid more',
  'morning morsel mortal mosaic moss most moth mother motion motive motor mould mound mount mourn mouse',
  'mouth move movie mow much muck mud muffin mug mule mumble mural murder murky murmur muscle museum',
  'mushroom music musk must mustard mute mutter mutual muzzle myself mystery myth nag nail naive naked',
  'name nap napkin narrow nasal nation native nature naval navy near neat neck need needle negate neglect',
  'neigh neither neon nephew nerve nest net nettle neutral never new news next nibble nice nickel niece',
  'night nimble nine ninth nip noble nod noise nomad none nook noon noose nor norm north nose nostril',
  'not notch note nothing notice notion noun novel novice now nozzle nuclear nudge nugget null numb number',
  'nurse nut nylon nymph oak oar oasis oat oath obey object oblige oboe obscure observe obtain obvious',
  'occur ocean octave october odd ode odor off offend offer office often oil oily okay old olive omen',
  'omit once one onion only onset onto onward opal open opera operate opinion oppose optic option oral',
  'orange orbit orchard ordeal order organ orient origin ornate orphan other otter ought ounce our oust',
  'out outer outfit outing outlaw outlet output outset oval oven over overt owe owl own oxide oxygen',
  'oyster ozone pace pack pact pad paddle page paid pail pain paint pair palace pale palm pamper pan',
  'panel panic pansy pant paper parade parcel pardon parent parish park parlor parrot parsley part partly',
  'party pass past pasta paste pastel pastor pasture pat patch patent path patient patrol patron pattern',
  'pause pave paw pawn pay payment pea peace peach peak peanut pear pearl peasant peat pebble peck peculiar',
  'pedal peel peer peg pelt pen penalty pencil penny people pepper per perch perfect peril period perish',
  'permit person pest pet petal petition petty phase phone photo phrase physic piano pick picnic picture',
  'pie piece pier pierce pig pigeon pike pile pilgrim pill pillar pillow pilot pin pinch pine pink pint',
  'pioneer pipe pirate pistol pit pitch pity pivot pixel place plague plain plan plane planet plank plant',
  'plaster plastic plate plateau play plea plead please pledge plenty pliers plight plod plot plow pluck',
  'plug plum plumb plume plump plunge plural plus plush pocket pod poem poet point poise poison poke',
  'polar pole police policy polish polite poll polo pond ponder pony pool poor pop poplar poppy popular',
  'porch pore pork port portal portion pose position possess post posture pot potato potent pouch poultry',
  'pounce pound pour pout powder power praise prance prank prawn pray preach precise prefer prefix premium',
  'prepare present preserve press presume pretend pretty prevail prevent prey price prick pride priest',
  'primary prime prince print prior prism prison private prize probe problem proceed process proclaim',
  'prod produce profit profound program progress project prolong promise promote prompt prone prong proof',
  'prop proper propose prose prosper protect protest proud prove provide prowl proxy prudent prune pry',
  'public pudding puddle puff pull pulp pulse puma pump pumpkin punch pupil puppy purchase pure purge',
  'purple purpose purse pursue push put putt puzzle pyramid python quack quaint quake qualify quality',
  'quantum quarrel quart quarter quartz quaver queen queer quell quench query quest question queue quick',
  'quiet quill quilt quip quirk quit quite quiver quiz quota quote rabbit race rack radar radiant radio',
  'radish raft rag rage raid rail rain raise rake rally ram ramble ramp ranch random range rank ransom',
  'rapid rare rascal rash rat rate rather ratio rattle raven raw ray razor reach react read ready real',
  'realm reap rear reason rebel rebound recall recede receipt receive recent recess recipe recite reckon',
  'record recover recruit rectify red redeem reduce reed reef reel refer refine reflect reform refrain',
  'refuge refund refuse regain regal regard regime region regret regular reign reject rejoice relate',
  'relax relay release relent relic relief religion relish rely remain remark remedy remind remnant remote',
  'remove render renew rent repair repeal repeat repel replace reply report repose repress reptile repute',
  'request require rescue research resent reserve reside resign resist resolve resort resource respect',
  'respond rest restore result resume retail retain retire retreat return reveal revel revenge revenue',
  'revere reverse review revise revive revolt revolve reward rhyme rhythm rib ribbon rice rich rid ridge',
  'ridicule rifle rift right rigid rim rind ring rinse riot rip ripe ripple rise risk rite ritual rival',
  'river road roam roar roast rob robe robin robot robust rock rocket rod rode rodent rogue role roll',
  'roman romance roof room roost root rope rose roster rosy rot rotate rough round rouse rout route rove',
  'row royal rub rubble ruby rudder rude rug rugged ruin rule rumble rumor run rung runner rural rush',
  'rust rustic rustle rut rye sable sack sacred sad saddle safe safety sag saga sage said sail saint',
  'sake salad salary sale salmon salon saloon salt salute same sample sand sane sank sap sash satin satire',
  'satisfy sauce saucer sausage savage save savor saw say scale scalp scan scandal scant scar scarce',
  'scare scarf scarlet scatter scene scenic scent scheme scholar school science scissor scoff scold scoop',
  'scope scorch score scorn scour scout scowl scramble scrap scrape scratch scrawl scream screen screw',
  'scribe script scroll scrub scuff sculpt sea seal seam search season seat second secret sect section',
  'secure sedan seduce see seed seek seem seen seep seize seldom select self sell semi senate send senior',
  'sense sent sentry sequel sequence serene serial series serious sermon serpent serum servant serve',
  'session set settle seven sever severe sew shabby shack shade shadow shaft shake shall shallow sham',
  'shame shape share shark sharp shatter shave shawl she shear sheath shed sheep sheer sheet shelf shell',
  'shelter shepherd sherry shield shift shin shine shingle ship shirt shiver shoal shock shoe shone shook',
  'shoot shop shore short shot should shoulder shout shove shovel show shower shred shrewd shriek shrill',
  'shrimp shrine shrink shroud shrub shrug shudder shuffle shun shut shy sick side siege sieve sift sigh',
  'sight sign signal silent silk sill silly silver simple simply since sincere sinew sing single sink',
  'sip sir siren sister sit site sixth sixty size skate sketch ski skid skill skim skin skip skirt skull',
  'skunk sky slab slack slain slam slander slang slant slap slash slate slave slay sled sleek sleep sleet',
  'sleeve sleigh slender slept slice slick slide slight slim slime sling slip slipper slit slogan slope',
  'slot sloth slouch slow sludge slug slum slump slur slush sly smack small smart smash smear smell smile',
  'smite smith smock smoke smooth smother smug snack snag snail snake snap snare snarl snatch sneak sneer',
  'sneeze sniff snip snob snoop snore snort snout snow snub snug soak soap soar sob sober social sock',
  'socket sod soda sofa soft soil solar sold soldier sole solemn solid solo solve some son song soon',
  'soot soothe sore sorrow sorry sort soul sound soup sour source south sow space spade span spare spark',
  'sparrow spasm spat spawn speak spear special speck speech speed spell spend spent sphere spice spider',
  'spike spill spin spine spiral spirit spit spite splash splice split spoil spoke sponge spool spoon',
  'sport spot spout sprain sprawl spray spread spring sprint sprout spruce spun spur spurn spy squad',
  'square squash squat squeak squeal squeeze squid squint squirrel stab stable stack staff stag stage',
  'stain stair stake stale stalk stall stamp stand staple star starch stare stark start startle starve',
  'state statue status stay steady steak steal steam steel steep steer stem stench step stereo stern',
  'stew stick stiff still stilt sting stint stir stitch stock stoic stole stomach stone stood stool stoop',
  'stop store stork storm story stout stove stow straight strain strait strand strange strap straw stray',
  'streak stream street stress stretch strew strict stride strife strike string strip stripe strive stroke',
  'stroll strong struck struggle strut stub stubble stuck stud student studio study stuff stumble stump',
  'stun stunt sturdy style suave subdue subject submit subsist subtle subtract suburb subway succeed',
  'such suck sudden suffer sugar suggest suit sulfur sulky sullen sultry sum summer summit summon sun',
  'sundae sunny super supper supply support suppose supreme sure surf surface surge surgeon surname surpass',
  'surplus surprise survey survive suspect suspend sustain swallow swam swamp swan swap swarm sway swear',
  'sweat sweep sweet swell swept swift swim swine swing swipe swirl switch swollen swoop sword swore',
  'sworn swung symbol symptom syrup system table tablet tack tackle tact tag tail tailor take tale talent',
  'talk tall tally tame tan tangle tank tap tape tar target tariff tarnish tart task taste tattoo taught',
  'taunt tavern tax taxi tea teach team tear tease tedious teem teeth tell temper temple tempo tempt',
  'ten tenant tend tender tennis tenor tense tent tenth tepid term terrace terrain terror test text texture',
  'than thank that thaw the theft their them theme then theory there these they thick thief thigh thimble',
  'thin thing think third thirst thirty this thistle thorn those though thought thousand thread threat',
  'three thresh threw thrift thrill thrive throat throb throne throng through throw thrust thud thumb',
  'thump thus thwart tick ticket tide tidy tie tier tiger tight tile till tilt timber time timid tin',
  'tinge tint tiny tip tire tissue title toad toast today toe together toil token told toll tomato tomb',
  'tone tongs tongue tonic tonight too took tool tooth top topaz topic topple torch torment torn torso',
  'toss total totem touch tough tour tow toward towel tower town toxic toy trace track tract trade traffic',
  'tragic trail train trait tramp trance transit trap trash travel tray tread treason treat treaty tree',
  'trek tremble trench trend trial tribe trick tried trifle trigger trim trio trip triple triumph trivial',
  'troll troop trophy tropic trot trouble trough trout truce truck trudge true trumpet trunk trust truth',
  'try tub tube tuck tuft tug tulip tumble tuna tundra tune tunnel turf turkey turn turnip turret turtle',
  'tusk tutor twelve twenty twice twig twilight twin twine twinge twirl twist twitch two type typical',
  'tyrant udder ugly ulcer ultra umbrella umpire unable unarmed unaware uncle uncover under undergo undo',
  'undue unearth uneasy unequal uneven unfair unfit unfold unhappy unicorn uniform unify union unique',
  'unit unite unity unjust unkind unknown unless unlike unlock unpack unrest unroll unsafe unseen untidy',
  'until unused unusual unveil unwise unwrap upheld uphill uphold upkeep upland uplift upon upper upright',
  'uproar upset upside upward urban urge urgent usage use useful usher usual usurp utensil utility utmost',
  'utter vacant vacate vacuum vague vain vale valet valid valley valor value valve van vane vanish vanity',
  'vapor variety various varnish vary vase vassal vast vat vault veal veer vehicle veil vein velvet vend',
  'veneer venom vent venture venue verb verbal verdict verge verify verse version versus vertex very',
  'vessel vest veto vex via vial vibrant vicar vice victim victor video view vigil vigor vile villa village',
  'villain vine vinegar vintage vinyl viola violate violent violet violin viper virtue virus visa visible',
  'vision visit visor vista visual vital vivid vocal vogue voice void volcano volley volume vote vouch',
  'vow vowel voyage vulgar wad wade wafer wag wage wagon waist wait waive wake walk wall wallet walnut',
  'walrus waltz wand wander wane want war ward warden wardrobe warm warn warp warrant warrior wart wary',
  'was wash wasp waste watch water wave wax way weak wealth weapon wear weary weasel weather weave web',
  'wedge weed week weep weigh weight weird welcome weld welfare well went wept were west wet whale wharf',
  'what wheat wheel when where which whiff while whim whine whip whirl whisk whisper whistle white whole',
  'whom whose why wick wicked wide widow width wield wife wig wild will willow wilt win wince winch wind',
  'window wine wing wink winner winter wipe wire wisdom wise wish wisp wit witch with wither within without',
  'witness witty wizard woke wolf woman wonder wood wool word wore work world worm worn worry worse worship',
  'worst worth would wound woven wrap wrath wreath wreck wrench wrest wretch wring wrinkle wrist writ',
  'write wrong wrote wrought wrung yacht yam yank yard yarn yawn year yearn yeast yell yellow yelp yes',
  'yet yield yodel yoke yolk yonder you young your youth zeal zebra zenith zero zest zigzag zinc zip',
  'zone zoo zoom',
];

/** Sorted ascending, so lookup is a binary search rather than a Set of 4000 strings. */
export const DICTIONARY: readonly string[] = PACKED.join(' ').split(' ');

export const MIN_WORD_LENGTH = 3;
export const MAX_WORD_LENGTH = 8;

/** True if `word` (lowercase) is in the dictionary. O(log n), no allocation. */
export function isWord(word: string): boolean {
  if (word.length < MIN_WORD_LENGTH || word.length > MAX_WORD_LENGTH) return false;
  let low = 0;
  let high = DICTIONARY.length - 1;
  while (low <= high) {
    const mid = (low + high) >> 1;
    const candidate = DICTIONARY[mid] as string;
    if (candidate === word) return true;
    if (candidate < word) low = mid + 1;
    else high = mid - 1;
  }
  return false;
}
