/**
 * Schema and migrations.
 *
 * Migrations are append-only and forward-only. Each one runs exactly once,
 * inside a transaction, and `user_version` records how far the database has
 * come. Never edit a migration that has shipped - add another.
 *
 * Everything here lives on the device. There is no server, no sync target and
 * no analytics sink; the only way data leaves is when the user explicitly sends
 * it to a peer.
 */
import type { SqliteDatabase } from './driver.js';

export interface Migration {
  readonly version: number;
  readonly name: string;
  readonly up: string;
}

export const MIGRATIONS: readonly Migration[] = [
  {
    version: 1,
    name: 'initial schema',
    up: `
-- The person using this device. Exactly one row, id = 'local'.
CREATE TABLE users (
  id                TEXT PRIMARY KEY,
  peer_id           TEXT NOT NULL UNIQUE,
  display_name      TEXT NOT NULL,
  avatar_emoji      TEXT,
  avatar_color      TEXT,
  identity_public   BLOB NOT NULL,
  device_id         TEXT NOT NULL,
  created_at        INTEGER NOT NULL,
  updated_at        INTEGER NOT NULL
);

-- Every peer we have ever seen, trusted or not.
CREATE TABLE peers (
  peer_id           TEXT PRIMARY KEY,
  display_name      TEXT NOT NULL,
  avatar_emoji      TEXT,
  avatar_color      TEXT,
  identity_public   BLOB NOT NULL,
  platform          TEXT,
  first_seen_at     INTEGER NOT NULL,
  last_seen_at      INTEGER NOT NULL,
  -- 'trusted' peers reconnect silently; 'known' need confirmation; 'blocked'
  -- are refused before the handshake even starts.
  trust_state       TEXT NOT NULL CHECK (trust_state IN ('trusted','known','blocked')),
  -- How the trust was established, for the security screen.
  verified_via      TEXT CHECK (verified_via IN ('qr','sas','none')),
  verified_at       INTEGER,
  notes             TEXT
);
CREATE INDEX idx_peers_trust ON peers(trust_state, last_seen_at DESC);

-- Physical devices belonging to a peer. One peer may carry several.
CREATE TABLE devices (
  device_id         TEXT PRIMARY KEY,
  peer_id           TEXT NOT NULL REFERENCES peers(peer_id) ON DELETE CASCADE,
  model             TEXT,
  platform          TEXT,
  app_version       TEXT,
  last_transport    TEXT,
  last_seen_at      INTEGER NOT NULL
);
CREATE INDEX idx_devices_peer ON devices(peer_id);

-- A record of each secure session, for the security and developer screens.
CREATE TABLE sessions (
  id                TEXT PRIMARY KEY,
  peer_id           TEXT NOT NULL REFERENCES peers(peer_id) ON DELETE CASCADE,
  transport         TEXT NOT NULL,
  protocol_version  INTEGER NOT NULL,
  started_at        INTEGER NOT NULL,
  ended_at          INTEGER,
  end_reason        TEXT,
  bytes_sent        INTEGER NOT NULL DEFAULT 0,
  bytes_received    INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX idx_sessions_peer ON sessions(peer_id, started_at DESC);

-- A one-to-one or group conversation.
CREATE TABLE conversations (
  id                TEXT PRIMARY KEY,
  kind              TEXT NOT NULL CHECK (kind IN ('direct','group')),
  title             TEXT,
  -- For 'direct', the peer on the other end. Null for groups.
  peer_id           TEXT REFERENCES peers(peer_id) ON DELETE CASCADE,
  group_id          TEXT,
  trip_id           TEXT,
  created_at        INTEGER NOT NULL,
  updated_at        INTEGER NOT NULL,
  last_message_at   INTEGER,
  unread_count      INTEGER NOT NULL DEFAULT 0,
  archived          INTEGER NOT NULL DEFAULT 0,
  muted             INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX idx_conversations_recent ON conversations(archived, last_message_at DESC);
CREATE UNIQUE INDEX idx_conversations_peer ON conversations(peer_id) WHERE peer_id IS NOT NULL;

CREATE TABLE groups (
  id                TEXT PRIMARY KEY,
  name              TEXT NOT NULL,
  avatar_emoji      TEXT,
  created_by        TEXT NOT NULL,
  created_at        INTEGER NOT NULL,
  updated_at        INTEGER NOT NULL,
  -- The peer currently acting as host. Nullable so host migration can be added
  -- without a schema change.
  host_peer_id      TEXT
);

CREATE TABLE group_members (
  group_id          TEXT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  peer_id           TEXT NOT NULL,
  role              TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('owner','member')),
  joined_at         INTEGER NOT NULL,
  left_at           INTEGER,
  PRIMARY KEY (group_id, peer_id)
);
CREATE INDEX idx_group_members_peer ON group_members(peer_id);

-- Chat messages. Content stays on the device.
CREATE TABLE messages (
  -- Globally unique, generated by the sender, so both devices agree on identity.
  id                TEXT PRIMARY KEY,
  conversation_id   TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  sender_peer_id    TEXT NOT NULL,
  kind              TEXT NOT NULL CHECK (kind IN ('text','image','file','voice','system','game')),
  body              TEXT,
  -- Sender's clock. Advisory: used for display, never for ordering.
  sent_at           INTEGER NOT NULL,
  -- Our clock when the message was created or received. Authoritative ordering.
  received_at       INTEGER NOT NULL,
  -- Monotonic per-conversation ordering key, assigned locally.
  sort_key          INTEGER NOT NULL,
  status            TEXT NOT NULL CHECK (status IN ('pending','sent','delivered','read','failed')),
  reply_to_id       TEXT REFERENCES messages(id) ON DELETE SET NULL,
  file_id           TEXT,
  deleted           INTEGER NOT NULL DEFAULT 0,
  -- Local-only bookkeeping for the reliability layer.
  outbound_seq      INTEGER
);
CREATE INDEX idx_messages_conversation ON messages(conversation_id, sort_key DESC);
CREATE INDEX idx_messages_status ON messages(status) WHERE status IN ('pending','failed');

CREATE TABLE reactions (
  message_id        TEXT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  peer_id           TEXT NOT NULL,
  emoji             TEXT NOT NULL,
  created_at        INTEGER NOT NULL,
  PRIMARY KEY (message_id, peer_id, emoji)
);

-- Files offered, sent or received.
CREATE TABLE files (
  id                TEXT PRIMARY KEY,
  name              TEXT NOT NULL,
  mime_type         TEXT NOT NULL,
  size_bytes        INTEGER NOT NULL,
  -- BLAKE2s/SHA-256 of the whole file, used for content matching in Sync.
  content_hash      BLOB NOT NULL,
  -- Where the bytes live on this device. Null until a transfer completes.
  local_path        TEXT,
  width             INTEGER,
  height            INTEGER,
  duration_ms       INTEGER,
  created_at        INTEGER NOT NULL
);
CREATE INDEX idx_files_hash ON files(content_hash);

CREATE TABLE transfers (
  id                TEXT PRIMARY KEY,
  file_id           TEXT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
  peer_id           TEXT NOT NULL,
  conversation_id   TEXT REFERENCES conversations(id) ON DELETE SET NULL,
  direction         TEXT NOT NULL CHECK (direction IN ('outgoing','incoming')),
  state             TEXT NOT NULL CHECK (state IN ('offered','accepted','declined','transferring','paused','complete','failed','cancelled')),
  chunk_size        INTEGER NOT NULL,
  total_chunks      INTEGER NOT NULL,
  -- Bitmap of received chunks, so a transfer resumes rather than restarting.
  received_bitmap   BLOB,
  bytes_transferred INTEGER NOT NULL DEFAULT 0,
  started_at        INTEGER,
  completed_at      INTEGER,
  error             TEXT,
  created_at        INTEGER NOT NULL,
  updated_at        INTEGER NOT NULL
);
CREATE INDEX idx_transfers_active ON transfers(state, updated_at DESC);
CREATE INDEX idx_transfers_peer ON transfers(peer_id);

-- One row per game that has been played.
CREATE TABLE game_sessions (
  id                TEXT PRIMARY KEY,
  game_id           TEXT NOT NULL,
  game_version      INTEGER NOT NULL,
  conversation_id   TEXT REFERENCES conversations(id) ON DELETE SET NULL,
  host_peer_id      TEXT NOT NULL,
  seed              INTEGER NOT NULL,
  players_json      TEXT NOT NULL,
  state             TEXT NOT NULL CHECK (state IN ('invited','declined','active','finished','abandoned')),
  -- Latest serialised game state, so an interrupted game resumes.
  snapshot          BLOB,
  winner_peer_id    TEXT,
  result            TEXT,
  started_at        INTEGER,
  finished_at       INTEGER,
  created_at        INTEGER NOT NULL,
  updated_at        INTEGER NOT NULL
);
CREATE INDEX idx_game_sessions_recent ON game_sessions(updated_at DESC);

-- The ordered action log. Replaying it reproduces the game exactly.
CREATE TABLE game_events (
  game_session_id   TEXT NOT NULL REFERENCES game_sessions(id) ON DELETE CASCADE,
  idx               INTEGER NOT NULL,
  player_peer_id    TEXT NOT NULL,
  action_seq        INTEGER NOT NULL,
  payload           BLOB NOT NULL,
  created_at        INTEGER NOT NULL,
  PRIMARY KEY (game_session_id, idx)
);

-- Watch-together sessions.
CREATE TABLE sync_sessions (
  id                TEXT PRIMARY KEY,
  conversation_id   TEXT REFERENCES conversations(id) ON DELETE SET NULL,
  host_peer_id      TEXT NOT NULL,
  file_id           TEXT REFERENCES files(id) ON DELETE SET NULL,
  content_hash      BLOB NOT NULL,
  content_name      TEXT NOT NULL,
  duration_ms       INTEGER,
  state             TEXT NOT NULL CHECK (state IN ('pending','ready','playing','paused','ended')),
  position_ms       INTEGER NOT NULL DEFAULT 0,
  playback_rate     REAL NOT NULL DEFAULT 1.0,
  -- Host clock at the moment position_ms was true.
  anchor_wall_ms    INTEGER,
  participants_json TEXT NOT NULL,
  created_at        INTEGER NOT NULL,
  updated_at        INTEGER NOT NULL
);

-- Trips group everything that happened on one journey.
CREATE TABLE trips (
  id                TEXT PRIMARY KEY,
  name              TEXT NOT NULL,
  emoji             TEXT,
  starts_on         TEXT,
  ends_on           TEXT,
  created_at        INTEGER NOT NULL,
  updated_at        INTEGER NOT NULL,
  archived          INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE trip_members (
  trip_id           TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  peer_id           TEXT NOT NULL,
  joined_at         INTEGER NOT NULL,
  PRIMARY KEY (trip_id, peer_id)
);

CREATE TABLE trip_notes (
  id                TEXT PRIMARY KEY,
  trip_id           TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  author_peer_id    TEXT NOT NULL,
  body              TEXT NOT NULL,
  created_at        INTEGER NOT NULL,
  updated_at        INTEGER NOT NULL
);
CREATE INDEX idx_trip_notes_trip ON trip_notes(trip_id, updated_at DESC);

-- Simple key/value store for preferences.
CREATE TABLE settings (
  key               TEXT PRIMARY KEY,
  value             TEXT NOT NULL,
  updated_at        INTEGER NOT NULL
);

-- Local-only diagnostic log. Never leaves the device.
CREATE TABLE event_log (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  at                INTEGER NOT NULL,
  level             TEXT NOT NULL,
  scope             TEXT NOT NULL,
  message           TEXT NOT NULL,
  data_json         TEXT
);
CREATE INDEX idx_event_log_at ON event_log(at DESC);
`,
  },
  {
    version: 2,
    name: 'advertisement keys for offline friend recognition',
    up: `
-- The two secrets behind a friend's rotating BLE advertisement token.
--
-- advertisement_key   theirs: lets us recognise them in a broadcast before we
--                     connect, which is what makes "Maria - Trusted friend"
--                     appear the moment she walks into range.
-- self_advertisement_key  ours, PER FRIENDSHIP rather than per device: if every
--                     friend saw the same token from us, two of them could
--                     compare notes and prove they had seen the same phone.
--
-- Both are exchanged inside the encrypted session during pairing, so a record
-- created from a scanned QR code has neither until the two devices have
-- actually met.
ALTER TABLE peers ADD COLUMN advertisement_key BLOB;
ALTER TABLE peers ADD COLUMN self_advertisement_key BLOB;
ALTER TABLE peers ADD COLUMN paired_at INTEGER;
`,
  },
];

export const LATEST_SCHEMA_VERSION = MIGRATIONS[MIGRATIONS.length - 1]?.version ?? 0;

export interface MigrationResult {
  readonly from: number;
  readonly to: number;
  readonly applied: readonly string[];
}

/** Apply every migration the database has not yet seen. */
export function migrate(db: SqliteDatabase): MigrationResult {
  const currentRow = db.prepare('PRAGMA user_version').get<{ user_version: number }>();
  const from = Number(currentRow?.user_version ?? 0);
  const applied: string[] = [];

  for (const migration of MIGRATIONS) {
    if (migration.version <= from) continue;
    db.transaction(() => {
      db.exec(migration.up);
      // PRAGMA does not accept bound parameters, and `version` comes only from
      // the constant table above - never from user input.
      db.exec(`PRAGMA user_version = ${migration.version}`);
    });
    applied.push(`${migration.version}: ${migration.name}`);
  }

  const toRow = db.prepare('PRAGMA user_version').get<{ user_version: number }>();
  return { from, to: Number(toRow?.user_version ?? from), applied };
}
