#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>

// Generated by React Native codegen from src/NativeAirLinkTransport.ts during
// `pod install`. Defines NativeAirLinkTransportSpec and NativeAirLinkTransportSpecBase,
// the latter supplying the typed emitters for the EventEmitter properties.
#import <AirLinkTransportSpec/AirLinkTransportSpec.h>

NS_ASSUME_NONNULL_BEGIN

/**
 * The TurboModule. Nothing but forwarding lives here.
 *
 * React Native's TurboModule machinery is C++ - `getTurboModule:` returns a
 * `std::shared_ptr<facebook::react::TurboModule>`, which Swift cannot express -
 * so the module class itself must be Objective-C++. The actual radio work lives
 * in Swift, behind the AirLinkTransportBridge class, using the adapter pattern
 * both Apple and the React Native documentation recommend.
 */
@interface RCTNativeAirLinkTransport : NativeAirLinkTransportSpecBase <NativeAirLinkTransportSpec>
@end

NS_ASSUME_NONNULL_END
