#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>

// Generated by React Native codegen from src/NativeAirLinkTransport.ts during
// `pod install`. Defines NativeAirLinkTransportSpec and the SpecBase class that
// supplies the typed emitters for the EventEmitter properties.
//
// This import - and therefore the whole interface declaration below - lives in
// the .mm rather than in a header ON PURPOSE. The generated spec drags in the
// C++ TurboModule machinery, and CocoaPods puts every public header of a pod
// into the umbrella header that Swift compiles its module from. A public header
// importing this would make the Swift half of this very pod fail to build with
// "'utility' file not found". Nothing outside this file needs the interface, so
// nothing outside this file sees it.
#import <AirLinkTransportSpec/AirLinkTransportSpec.h>

// The Swift half of this module. Xcode generates this header from every @objc
// declaration in the pod's Swift sources; the pod is named "airlink-transport",
// so its module name is "airlink_transport". The angle-bracket form is the one
// that works when the pod is built as a framework, the quoted form when it is
// built as a static library - which is React Native's default. Probing for both
// keeps this file correct either way.
// The generated Swift header below declares our @objc classes' conformance to
// UNUserNotificationCenterDelegate, AVAudioRecorderDelegate and
// AVAudioPlayerDelegate. Those protocol names appear in it unqualified, so every
// translation unit that includes the header has to have the frameworks in scope
// FIRST or it fails with "cannot find protocol declaration" - a confusing error,
// because the file it points at is generated and correct.
#import <UserNotifications/UserNotifications.h>
#import <AVFoundation/AVFoundation.h>

#if __has_include(<airlink_transport/airlink_transport-Swift.h>)
#import <airlink_transport/airlink_transport-Swift.h>
#else
#import "airlink_transport-Swift.h"
#endif

/**
 * The TurboModule. Nothing but forwarding lives here.
 *
 * React Native's TurboModule machinery is C++ - `getTurboModule:` returns a
 * `std::shared_ptr<facebook::react::TurboModule>`, which Swift cannot express -
 * so the module class itself must be Objective-C++. The actual radio work lives
 * in Swift, behind AirLinkTransportBridge, using the adapter pattern both Apple
 * and the React Native documentation recommend.
 */
@interface RCTNativeAirLinkTransport : NativeAirLinkTransportSpecBase <NativeAirLinkTransportSpec, AirLinkTransportBridgeDelegate>
@end

/**
 * Pure forwarding. Every method hands off to the Swift bridge and wires the
 * promise callbacks; every event comes back through the delegate and is emitted
 * with the codegen-generated typed emitters.
 *
 * There is deliberately no logic here at all. If something needs a decision
 * made, it belongs in Swift (radio behaviour) or in TypeScript (protocol
 * behaviour), never in the glue.
 */
@implementation RCTNativeAirLinkTransport {
  AirLinkTransportBridge *_bridge;
}

RCT_EXPORT_MODULE(NativeAirLinkTransport)

- (instancetype)init {
  if (self = [super init]) {
    _bridge = [AirLinkTransportBridge shared];
    _bridge.delegate = self;
  }
  return self;
}

// The generated SpecBase derives from NSObject, so there is no super
// implementation to chain to; dropping the delegate is all the teardown this
// module needs.
- (void)invalidate {
  if (_bridge.delegate == self) {
    _bridge.delegate = nil;
  }
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params {
  return std::make_shared<facebook::react::NativeAirLinkTransportSpecJSI>(params);
}

#pragma mark - Capability and permissions

- (void)getCapabilities:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject {
  [_bridge getCapabilitiesWithResolve:^(NSDictionary *value) { resolve(value); }
                               reject:^(NSString *code, NSString *message) { reject(code, message, nil); }];
}

- (void)requestPermissions:(NSArray *)transports
                   resolve:(RCTPromiseResolveBlock)resolve
                    reject:(RCTPromiseRejectBlock)reject {
  [_bridge requestPermissions:transports
                      resolve:^(NSDictionary *value) { resolve(value); }
                       reject:^(NSString *code, NSString *message) { reject(code, message, nil); }];
}

- (void)openSettings {
  [_bridge openSettings];
}

#pragma mark - Lifecycle

- (void)start:(NSString *)serviceUuid
    rxCharacteristicUuid:(NSString *)rxCharacteristicUuid
    txCharacteristicUuid:(NSString *)txCharacteristicUuid
      bonjourServiceType:(NSString *)bonjourServiceType
                 resolve:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject {
  [_bridge startWithServiceUuid:serviceUuid
                             rx:rxCharacteristicUuid
                             tx:txCharacteristicUuid
                 bonjourService:bonjourServiceType
                        resolve:^{ resolve(nil); }
                         reject:^(NSString *code, NSString *message) { reject(code, message, nil); }];
}

- (void)stop:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject {
  [_bridge stopWithResolve:^{ resolve(nil); }
                    reject:^(NSString *code, NSString *message) { reject(code, message, nil); }];
}

#pragma mark - Advertising and discovery

- (void)startAdvertising:(NSString *)transport
                   token:(NSString *)token
             displayName:(NSString *)displayName
             discoveryId:(NSString *)discoveryId
                 resolve:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject {
  [_bridge startAdvertising:transport
                      token:token
                displayName:displayName
                discoveryId:discoveryId
                    resolve:^{ resolve(nil); }
                     reject:^(NSString *code, NSString *message) { reject(code, message, nil); }];
}

- (void)stopAdvertising:(NSString *)transport
                resolve:(RCTPromiseResolveBlock)resolve
                 reject:(RCTPromiseRejectBlock)reject {
  [_bridge stopAdvertising:transport
                   resolve:^{ resolve(nil); }
                    reject:^(NSString *code, NSString *message) { reject(code, message, nil); }];
}

- (void)startDiscovery:(NSString *)transport
               resolve:(RCTPromiseResolveBlock)resolve
                reject:(RCTPromiseRejectBlock)reject {
  [_bridge startDiscovery:transport
                  resolve:^{ resolve(nil); }
                   reject:^(NSString *code, NSString *message) { reject(code, message, nil); }];
}

- (void)stopDiscovery:(NSString *)transport
              resolve:(RCTPromiseResolveBlock)resolve
               reject:(RCTPromiseRejectBlock)reject {
  [_bridge stopDiscovery:transport
                 resolve:^{ resolve(nil); }
                  reject:^(NSString *code, NSString *message) { reject(code, message, nil); }];
}

#pragma mark - Links

/**
 * `timeoutMs` is NSInteger, and the type is load-bearing.
 *
 * The spec declares it `Int32`, so codegen puts `NSInteger` in the protocol.
 * This was written as `double`, which compiles - a selector matches on its name
 * - but does not work: on arm64 integers are passed in x registers and doubles
 * in v registers, so the argument after the mismatch is read from the wrong
 * place. `resolve` and `reject` arrived as garbage pointers and retaining one
 * segfaulted the app the instant anybody pressed Connect.
 *
 * Clang does warn about this ("conflicting parameter types in implementation").
 * The build script used to drop every warning on the floor; it no longer does.
 */
- (void)connect:(NSString *)transport
     endpointId:(NSString *)endpointId
      timeoutMs:(NSInteger)timeoutMs
        resolve:(RCTPromiseResolveBlock)resolve
         reject:(RCTPromiseRejectBlock)reject {
  [_bridge connect:transport
        endpointId:endpointId
         timeoutMs:timeoutMs
           resolve:^(NSString *linkId) { resolve(linkId); }
            reject:^(NSString *code, NSString *message) { reject(code, message, nil); }];
}

- (void)disconnect:(NSString *)linkId
            reason:(NSString *)reason
           resolve:(RCTPromiseResolveBlock)resolve
            reject:(RCTPromiseRejectBlock)reject {
  [_bridge disconnect:linkId
               reason:reason
              resolve:^{ resolve(nil); }
               reject:^(NSString *code, NSString *message) { reject(code, message, nil); }];
}

- (void)send:(NSString *)linkId
        data:(NSString *)data
    reliable:(BOOL)reliable
     resolve:(RCTPromiseResolveBlock)resolve
      reject:(RCTPromiseRejectBlock)reject {
  [_bridge send:linkId
           data:data
       reliable:reliable
        resolve:^{ resolve(nil); }
         reject:^(NSString *code, NSString *message) { reject(code, message, nil); }];
}

- (void)getLinkMetrics:(NSString *)linkId
               resolve:(RCTPromiseResolveBlock)resolve
                reject:(RCTPromiseRejectBlock)reject {
  [_bridge getLinkMetrics:linkId
                  resolve:^(NSDictionary *value) { resolve(value); }
                   reject:^(NSString *code, NSString *message) { reject(code, message, nil); }];
}

#pragma mark - Wi-Fi handoff

- (void)createHotspot:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject {
  [_bridge createHotspotWithResolve:^(NSDictionary *value) { resolve(value); }
                             reject:^(NSString *code, NSString *message) { reject(code, message, nil); }];
}

- (void)stopHotspot:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject {
  [_bridge stopHotspotWithResolve:^{ resolve(nil); }
                           reject:^(NSString *code, NSString *message) { reject(code, message, nil); }];
}

- (void)joinHotspot:(NSString *)ssid
         passphrase:(NSString *)passphrase
            resolve:(RCTPromiseResolveBlock)resolve
             reject:(RCTPromiseRejectBlock)reject {
  [_bridge joinHotspot:ssid
            passphrase:passphrase
               resolve:^(NSNumber *value) { resolve(value); }
                reject:^(NSString *code, NSString *message) { reject(code, message, nil); }];
}

- (void)leaveHotspot:(NSString *)ssid
             resolve:(RCTPromiseResolveBlock)resolve
              reject:(RCTPromiseRejectBlock)reject {
  [_bridge leaveHotspot:ssid
                resolve:^{ resolve(nil); }
                 reject:^(NSString *code, NSString *message) { reject(code, message, nil); }];
}

#pragma mark - AirLinkTransportBridgeDelegate

- (void)emitPeerDiscovered:(NSDictionary *)payload { [self emitOnPeerDiscovered:payload]; }
- (void)emitPeerLost:(NSDictionary *)payload { [self emitOnPeerLost:payload]; }
- (void)emitLinkOpened:(NSDictionary *)payload { [self emitOnLinkOpened:payload]; }
- (void)emitLinkState:(NSDictionary *)payload { [self emitOnLinkState:payload]; }
- (void)emitData:(NSDictionary *)payload { [self emitOnData:payload]; }
- (void)emitMtuChanged:(NSDictionary *)payload { [self emitOnMtuChanged:payload]; }
- (void)emitAvailabilityChanged:(NSDictionary *)payload { [self emitOnAvailabilityChanged:payload]; }
- (void)emitLog:(NSDictionary *)payload { [self emitOnLog:payload]; }

@end
