#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>

// Generated by React Native codegen from src/NativeAirLinkNotifications.ts
// during `pod install`. It lands in the same AirLinkTransportSpec library as
// the transport's spec because one pod produces one codegen library; the two
// modules inside it are otherwise completely independent, which is the whole
// point of them being separate specs.
//
// Imported in the .mm rather than in a header for the reason spelled out at the
// top of RCTNativeAirLinkTransport.mm: this header drags in the C++ TurboModule
// machinery, and a public header of this pod that imported it would break the
// Swift half of the very same pod.
#import <AirLinkTransportSpec/AirLinkTransportSpec.h>

// The generated Swift header below declares our @objc classes' conformance to
// UNUserNotificationCenterDelegate, AVAudioRecorderDelegate and
// AVAudioPlayerDelegate. Those protocol names appear in it unqualified, so every
// translation unit that includes the header has to have the frameworks in scope
// FIRST or it fails with "cannot find protocol declaration" - a confusing error,
// because the file it points at is generated and correct.
#import <UserNotifications/UserNotifications.h>
#import <AVFoundation/AVFoundation.h>

#if __has_include(<airlink_transport/airlink_transport-Swift.h>)
#import <airlink_transport/airlink_transport-Swift.h>
#else
#import "airlink_transport-Swift.h"
#endif

/**
 * The local-notifications TurboModule. Forwarding only, like every other module
 * in this pod: the OS work is in Notifications/LocalNotifications.swift and the
 * decisions are in TypeScript.
 */
@interface RCTNativeAirLinkNotifications : NativeAirLinkNotificationsSpecBase <NativeAirLinkNotificationsSpec, AirLinkNotificationsDelegate>
@end

@implementation RCTNativeAirLinkNotifications {
  LocalNotifications *_notifications;
}

RCT_EXPORT_MODULE(NativeAirLinkNotifications)

/**
 * The one piece of work in this pod that cannot wait for JavaScript.
 *
 * A load-time C constructor runs while the binary is being loaded, before
 * `main` - the same moment `+load` would, and it has to be a constructor rather
 * than `+load` because RCT_EXPORT_MODULE already defines one for this class
 * (RCTBridgeModule.h) and a second is a duplicate declaration. That is far
 * earlier than this module is otherwise constructed - TurboModules are lazy, so
 * nothing here exists until JS first imports it - and it is the only way to have
 * claimed UNUserNotificationCenter's delegate by the time the app finishes
 * launching, which Apple requires or the tap that launched the app is never
 * reported at all. `installDelegateEarly` only registers for the launch
 * notification; it touches no UI and allocates almost nothing, so it is safe at
 * this point in startup.
 */
__attribute__((constructor)) static void AirLinkInstallNotificationDelegate(void) {
  [LocalNotifications installDelegateEarly];
}

- (instancetype)init {
  if (self = [super init]) {
    _notifications = [LocalNotifications shared];
    _notifications.delegate = self;
    // Belt and braces. The +load path covers a cold launch; this covers the
    // case where something else claimed the delegate after launch, which would
    // otherwise leave taps going nowhere with no symptom but a dead banner.
    [_notifications claimDelegate];
  }
  return self;
}

- (void)invalidate {
  if (_notifications.delegate == self) {
    _notifications.delegate = nil;
  }
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params {
  return std::make_shared<facebook::react::NativeAirLinkNotificationsSpecJSI>(params);
}

#pragma mark - Permission

- (void)getPermission:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject {
  [_notifications getPermissionWithResolve:^(NSString *value) { resolve(value); }];
}

- (void)requestPermission:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject {
  [_notifications requestPermissionWithResolve:^(NSString *value) { resolve(value); }];
}

#pragma mark - Posting

- (void)present:(NSString *)identifier
          title:(NSString *)title
           body:(NSString *)body
       threadId:(NSString *)threadId
       dataJson:(NSString *)dataJson
        resolve:(RCTPromiseResolveBlock)resolve
         reject:(RCTPromiseRejectBlock)reject {
  [_notifications present:identifier
                     title:title
                      body:body
                  threadId:threadId
                  dataJson:dataJson
                   resolve:^{ resolve(nil); }
                    reject:^(NSString *code, NSString *message) { reject(code, message, nil); }];
}

/**
 * `count` is NSInteger, and the type is load-bearing - see the long note on
 * `connect:` in RCTNativeAirLinkTransport.mm. The spec says Int32, so codegen
 * puts NSInteger in the protocol; writing `double` here would compile, match by
 * selector name, and then hand the promise blocks the wrong registers.
 */
- (void)setBadgeCount:(NSInteger)count
              resolve:(RCTPromiseResolveBlock)resolve
               reject:(RCTPromiseRejectBlock)reject {
  [_notifications setBadgeCount:count
                        resolve:^{ resolve(nil); }
                         reject:^(NSString *code, NSString *message) { reject(code, message, nil); }];
}

#pragma mark - Clearing

- (void)clearThread:(NSString *)threadId
            resolve:(RCTPromiseResolveBlock)resolve
             reject:(RCTPromiseRejectBlock)reject {
  [_notifications clearThread:threadId resolve:^{ resolve(nil); }];
}

- (void)clearAll:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject {
  [_notifications clearAllWithResolve:^{ resolve(nil); }];
}

#pragma mark - The launch tap

- (void)consumeInitialOpen:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject {
  [_notifications consumeInitialOpenWithResolve:^(NSString *json) { resolve(json); }];
}

#pragma mark - AirLinkNotificationsDelegate

- (void)emitNotificationOpened:(NSDictionary *)payload { [self emitOnNotificationOpened:payload]; }
- (void)emitNotificationPresented:(NSDictionary *)payload { [self emitOnNotificationPresented:payload]; }

@end
