#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>

// Generated by React Native codegen from src/NativeAirLinkAudio.ts during
// `pod install`. Imported here rather than from a header for the reason given
// at the top of RCTNativeAirLinkTransport.mm - it pulls in the C++ TurboModule
// machinery, which must not reach the pod's Swift umbrella header.
#import <AirLinkTransportSpec/AirLinkTransportSpec.h>

// The generated Swift header below declares our @objc classes' conformance to
// UNUserNotificationCenterDelegate, AVAudioRecorderDelegate and
// AVAudioPlayerDelegate. Those protocol names appear in it unqualified, so every
// translation unit that includes the header has to have the frameworks in scope
// FIRST or it fails with "cannot find protocol declaration" - a confusing error,
// because the file it points at is generated and correct.
#import <UserNotifications/UserNotifications.h>
#import <AVFoundation/AVFoundation.h>

#if __has_include(<airlink_transport/airlink_transport-Swift.h>)
#import <airlink_transport/airlink_transport-Swift.h>
#else
#import "airlink_transport-Swift.h"
#endif

/**
 * The voice-message TurboModule. Forwarding only; AVFoundation lives in
 * Audio/AudioRecorder.swift.
 */
@interface RCTNativeAirLinkAudio : NativeAirLinkAudioSpecBase <NativeAirLinkAudioSpec, AirLinkAudioDelegate>
@end

@implementation RCTNativeAirLinkAudio {
  AudioRecorder *_audio;
}

RCT_EXPORT_MODULE(NativeAirLinkAudio)

- (instancetype)init {
  if (self = [super init]) {
    _audio = [AudioRecorder shared];
    _audio.delegate = self;
  }
  return self;
}

/**
 * Tearing down without stopping would leave the audio session active and the
 * microphone indicator lit after a reload, which is exactly the sort of thing a
 * reviewer notices.
 */
- (void)invalidate {
  [_audio cancelRecordingWithResolve:^{}];
  [_audio stopPlaybackWithResolve:^{}];
  if (_audio.delegate == self) {
    _audio.delegate = nil;
  }
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params {
  return std::make_shared<facebook::react::NativeAirLinkAudioSpecJSI>(params);
}

#pragma mark - Permission

- (void)getPermission:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject {
  [_audio getPermissionWithResolve:^(NSString *value) { resolve(value); }];
}

- (void)requestPermission:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject {
  [_audio requestPermissionWithResolve:^(BOOL granted) { resolve(@(granted)); }];
}

#pragma mark - Recording

- (void)startRecording:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject {
  [_audio startRecordingWithResolve:^{ resolve(nil); }
                             reject:^(NSString *code, NSString *message) { reject(code, message, nil); }];
}

- (void)stopRecording:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject {
  [_audio stopRecordingWithResolve:^(NSDictionary *value) { resolve(value); }
                            reject:^(NSString *code, NSString *message) { reject(code, message, nil); }];
}

- (void)cancelRecording:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject {
  [_audio cancelRecordingWithResolve:^{ resolve(nil); }];
}

#pragma mark - Playback

- (void)play:(NSString *)path
     resolve:(RCTPromiseResolveBlock)resolve
      reject:(RCTPromiseRejectBlock)reject {
  [_audio play:path
       resolve:^{ resolve(nil); }
        reject:^(NSString *code, NSString *message) { reject(code, message, nil); }];
}

- (void)stopPlayback:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject {
  [_audio stopPlaybackWithResolve:^{ resolve(nil); }];
}

#pragma mark - AirLinkAudioDelegate

- (void)emitLevel:(NSDictionary *)payload { [self emitOnLevel:payload]; }
- (void)emitPlaybackProgress:(NSDictionary *)payload { [self emitOnPlaybackProgress:payload]; }
- (void)emitPlaybackFinished:(NSDictionary *)payload { [self emitOnPlaybackFinished:payload]; }

@end
